// 35 — AIO Sandbox (all-in-one)
//
// Demonstrates the full FC SDK surface in a single script:
//   createSandbox (ingress) → files.upload → streamCommand (install) →
//   runCommand (daemonize server) → waitForPortReady → fetch ingress URL →
//   files.download → destroy
//
// An LLM agent generates the page content served over ingress — the AI
// output is injected into the sandbox via files.upload rather than printed
// to stdout, proving the complete agent → sandbox → public-URL pipeline.

import Anthropic from "@anthropic-ai/sdk";
import { FcClient } from "fc-sandbox-sdk";

const SHAPE = "s-2vcpu-2gb";
const ROOTFS = "devbox:1";
const PORT = 8000;

const fc = new FcClient({
  baseUrl: process.env.FC_BASE_URL,
});

const anthropic = new Anthropic({
  baseURL: process.env.ANTHROPIC_BASE_URL,
  apiKey: process.env.ANTHROPIC_AUTH_TOKEN,
  defaultHeaders: process.env.ANTHROPIC_MODEL
    ? { "X-Model-Override": process.env.ANTHROPIC_MODEL }
    : undefined,
});

// ── 1. Prompt the LLM to generate an HTML page ───────────────────────────────
console.log("[1/7] asking LLM to generate an HTML page...");
const resp = await anthropic.messages.create({
  model: process.env.ANTHROPIC_MODEL ?? "claude-haiku-4-5",
  max_tokens: 512,
  messages: [
    {
      role: "user",
      content:
        "Generate a complete self-contained HTML page (no external resources) " +
        "titled 'FC Sandbox' with a heading saying 'Running on FC' and a short " +
        "paragraph about how the page was generated by an AI and served from an " +
        "FC microVM sandbox. Reply with the raw HTML only — no markdown fences, " +
        "no prose.",
    },
  ],
});

const htmlContent = resp.content
  .filter((b): b is Anthropic.TextBlock => b.type === "text")
  .map((b) => b.text)
  .join("\n")
  .trim()
  .replace(/^```[a-z]*\n?/i, "")
  .replace(/```$/, "")
  .trim();

if (!htmlContent) throw new Error("LLM returned empty content");
console.log(`      got ${htmlContent.length} bytes of HTML`);

// ── 2. Create sandbox with ingress ────────────────────────────────────────────
console.log("[2/7] creating sandbox with ingress...");
const sandbox = await fc.createSandbox({
  shape: SHAPE,
  rootfs: ROOTFS,
  ingress_enabled: true,
});
console.log(`      sandbox: ${sandbox.id}  ip: ${sandbox.ip}`);
// Force http:// — TLS cert not provisioned on ingress today; http is
// forward-compatible with the infrastructure roadmap.
const previewUrl = sandbox.previewUrl(PORT).replace(/^https:\/\//, "http://");
console.log(`      preview URL: ${previewUrl}`);

try {
  // ── 3. Upload the AI-generated page into the sandbox ─────────────────────
  console.log("[3/7] uploading AI-generated page into sandbox...");
  await sandbox.files.upload("/srv/index.html", htmlContent);
  console.log("      uploaded /srv/index.html");

  // ── 4. Stream install output (proves streamCommand) ───────────────────────
  // Install a known-good version of python3 and confirm it's present.
  // devbox:1 ships Python 3 — this step just validates the environment and
  // demonstrates streamCommand's async iterator interface.
  console.log("[4/7] streaming environment check (streamCommand)...");
  let streamLines = 0;
  for await (const ev of sandbox.streamCommand("bash", [
    "-c",
    "python3 --version && echo 'env-ok'",
  ])) {
    if (ev.type === "stdout" || ev.type === "stderr") {
      process.stdout.write(`      stream> ${ev.data}`);
      streamLines++;
    }
    if (ev.type === "exit") {
      if (ev.exitCode !== 0) throw new Error(`env check failed: exit ${ev.exitCode}`);
      break;
    }
  }
  console.log(`      streamed ${streamLines} line(s)`);

  // ── 5. Daemonise HTTP server on 0.0.0.0 (required for ingress) ───────────
  // Use `;` before nohup (not `&&`) so runCommand does not wait for the
  // backgrounded process — `&&` holds the /exec pipe open indefinitely.
  console.log("[5/7] starting python HTTP server on 0.0.0.0:8000...");
  await sandbox.runCommand("bash", [
    "-c",
    `mkdir -p /srv ; nohup setsid python3 -m http.server ${PORT} --directory /srv --bind 0.0.0.0 </dev/null >/tmp/httpd.log 2>&1 &`,
  ]);

  // ── 6. Wait for port to become reachable via ingress ─────────────────────
  console.log("[6/7] waiting for ingress to forward traffic...");
  await sandbox.waitForPortReady(PORT, { timeoutMs: 60_000 });
  console.log("      port ready");

  // Fetch the page through the public ingress URL and print a snippet.
  const pageResp = await fetch(previewUrl);
  const body = await pageResp.text();
  console.log(`      HTTP ${pageResp.status} — ${body.length} bytes`);
  console.log(`      preview: ${body.slice(0, 120).replace(/\s+/g, " ").trim()}...`);

  // ── 7. Download the file back to prove the full files round-trip ──────────
  console.log("[7/7] downloading /srv/index.html back from sandbox...");
  const downloaded = await sandbox.files.download("/srv/index.html");
  const downloadedText = Buffer.from(downloaded).toString("utf8");
  const match = downloadedText.trim() === htmlContent.trim();
  console.log(`      download OK — ${downloaded.byteLength} bytes, content-match: ${match}`);

  console.log("\nall-in-one pipeline verified end-to-end.");
  console.log(`preview URL: ${previewUrl}`);
} finally {
  console.log("\ndestroying sandbox...");
  await sandbox.destroy().catch(() => {});
  console.log(`destroyed: ${sandbox.id}`);
}
