#!/usr/bin/env bun
// Regenerates the example catalog (in examples/README.md and llms.txt) and the
// llms-full.txt context bundle from examples/manifest.json — the single source
// of truth for the example index.
//
//   bun run docs:gen     write the generated regions/files
//   bun run docs:check   verify they are in sync (exit 1 on drift); used in CI
//
// examples/README.md and llms.txt each carry a `<!-- BEGIN/END GENERATED -->`
// region that this script owns. llms-full.txt is generated in full.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const read = (rel) => readFileSync(join(ROOT, rel), "utf8");
const manifest = JSON.parse(read("examples/manifest.json"));
const examples = manifest.examples;

const TICK = "`";
const markers = (name) => ({
  begin: `<!-- BEGIN GENERATED: ${name} (do not edit; run ${TICK}bun run docs:gen${TICK}) -->`,
  end: `<!-- END GENERATED: ${name} -->`,
});

function replaceRegion(content, name, body) {
  const { begin, end } = markers(name);
  const bi = content.indexOf(begin);
  const ei = content.indexOf(end);
  if (bi === -1 || ei === -1) {
    throw new Error(`gen-docs: GENERATED markers for "${name}" not found`);
  }
  return `${content.slice(0, bi + begin.length)}\n${body}\n${content.slice(ei)}`;
}

// ---- renderers ------------------------------------------------------------

function renderReadmeCatalog() {
  const header =
    "| # | Example | What it shows | Key SDK primitives | Setup |\n| --- | --- | --- | --- | --- |";
  const rows = examples.map((e) => {
    const setup = e.status === "stable" ? "—" : "extra";
    return `| ${e.id} | [${e.dir}](${e.dir}/) | ${e.summary} | ${e.primitives.join(", ")} | ${setup} |`;
  });
  const noted = examples.filter((e) => e.notes || e.status !== "stable");
  const notes = noted.map((e) => {
    const tag = e.status !== "stable" ? "**needs extra setup** — " : "";
    return `- **${e.id} ${e.slug}** — ${tag}${e.notes ?? "external service or extra secrets required."}`;
  });
  const legend = "\nSetup `extra` = needs an external service or extra secrets; excluded from CI.";
  const notesBlock = notes.length ? `\n**Notes**\n\n${notes.join("\n")}\n` : "";
  return `${header}\n${rows.join("\n")}\n${legend}\n${notesBlock}`;
}

function renderLlmsExamples() {
  return examples.map((e) => `- [${e.dir}](examples/${e.dir}/) — ${e.summary}`).join("\n");
}

function renderLlmsFull(llmsTxt) {
  const sections = [
    "# fc-sandbox-sdk — full context bundle",
    "> Generated by scripts/gen-docs.mjs from README.md, docs/, and llms.txt.\n> Do not edit by hand; run `bun run docs:gen`.",
    read("README.md"),
    read("docs/quickstart.md"),
    read("docs/how-to/streaming.md"),
    read("docs/how-to/error-handling.md"),
    read("docs/how-to/observability.md"),
    llmsTxt,
  ];
  // Strip per-line trailing whitespace so the bundle is stable under the
  // repo's trailing-whitespace pre-commit hook (source docs may carry it).
  return `${sections.join("\n\n---\n\n")}\n`.replace(/[ \t]+$/gm, "");
}

// ---- plan the writes ------------------------------------------------------

const outputs = {};

outputs["examples/README.md"] = replaceRegion(
  read("examples/README.md"),
  "examples",
  renderReadmeCatalog(),
);

const llmsTxt = replaceRegion(read("llms.txt"), "examples", renderLlmsExamples());
outputs["llms.txt"] = llmsTxt;
outputs["llms-full.txt"] = renderLlmsFull(llmsTxt);

// ---- write or check -------------------------------------------------------

let drift = false;
for (const [rel, content] of Object.entries(outputs)) {
  const path = join(ROOT, rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === content) continue;
  if (CHECK) {
    drift = true;
    console.error(`out of sync: ${relative(ROOT, path)} — run \`bun run docs:gen\``);
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}

if (CHECK) {
  if (drift) process.exit(1);
  console.log("docs in sync with examples/manifest.json");
}
